import assert from 'node:assert/strict'; import { readFile } from 'node:fs/promises'; import test from 'node:test';
import { MAX_FRAME_BYTES, MAX_TRACE_ENTRIES, TransportStateError, TransportStateReducer } from '../src/raw-core/transport-state.ts';
const open = () => { let n = 0; const reducer = new TransportStateReducer({ nowMs: () => n }); reducer.start(); reducer.markOpen(); return { reducer, set: x => { n = x; } }; }; const fail = (fn, code) => assert.throws(fn, e => e instanceof TransportStateError && e.code === code);
const FIXTURE_KEYS = ['events', 'inboundHex', 'kind', 'notLive', 'outboundHex', 'source', 'synthetic'];
const EXPECTED_EVENTS = ['start', 'markOpen', 'enqueueOutbound', 'receiveInbound', 'takeOutbound', 'commitOutbound', 'takeInbound', 'beginClose', 'markClosed'];
const LIVE_MARKER = /\b(?:url|uri|https?|wss?|host|hostname|domain|endpoint|ip|address|port|telegram|dc(?:[-_:]?\d+)?|api(?:[_ -]?(?:id|hash))?|credential|token|password|phone|otp)\b|\b\d{1,3}(?:\.\d{1,3}){3}\b/iu;
function validateFixture(input) {
  assert.ok(input && typeof input === 'object' && !Array.isArray(input), 'invalid fixture');
  assert.deepEqual(Object.keys(input).sort(), FIXTURE_KEYS, 'invalid fixture keys');
  assert.equal(input.kind, 'synthetic-transport-state-v1'); assert.equal(input.synthetic, true); assert.equal(input.notLive, true); assert.equal(input.source, 'project-authored');
  for (const key of ['outboundHex', 'inboundHex']) assert.match(input[key], /^(?:[0-9a-f]{2})+$/, `invalid ${key}`);
  assert.deepEqual(input.events, EXPECTED_EVENTS, 'invalid lifecycle events');
  const visit = value => { if (typeof value === 'string') assert.doesNotMatch(value, LIVE_MARKER, 'forbidden live marker'); else if (Array.isArray(value)) value.forEach(visit); else if (value && typeof value === 'object') Object.values(value).forEach(visit); };
  visit(input); return input;
}
const decodeHex = hex => Uint8Array.from(hex.match(/../g), pair => Number.parseInt(pair, 16));
const happyFixture = async () => validateFixture(JSON.parse(await readFile(new URL('./fixtures/transport/happy.json', import.meta.url))));
test('lifecycle terminal state and frozen records', () => { const { reducer } = open(); reducer.beginClose(); reducer.markClosed(); const trace = JSON.stringify(reducer.trace()); assert.ok(Object.isFrozen(reducer.snapshot()) && Object.isFrozen(reducer.trace())); fail(() => reducer.start(), 'closed'); assert.equal(JSON.stringify(reducer.trace()), trace); assert.doesNotMatch(trace, /token|frame|endpoint/i); });
test('owned FIFO outbound and exact commit', () => { const { reducer } = open(); const input = new Uint8Array([1, 2]); reducer.enqueueOutbound(input); input[0] = 9; const item = reducer.takeOutbound(); assert.deepEqual([...item.frame], [1, 2]); item.frame[0] = 8; assert.equal(reducer.takeOutbound(), undefined); fail(() => reducer.commitOutbound(item.token, 1), 'invalid-input'); assert.equal(reducer.snapshot().outboundCount, 0); });
test('inbound clone and max frame', () => { const { reducer } = open(); const input = new Uint8Array([3]); reducer.receiveInbound(input); input[0] = 8; assert.deepEqual([...reducer.takeInbound()], [3]); reducer.enqueueOutbound(new Uint8Array(MAX_FRAME_BYTES)); assert.equal(reducer.snapshot().outboundBytes, MAX_FRAME_BYTES); });
test('clock rollback and cancellation clean state', () => { const { reducer, set } = open(); reducer.enqueueOutbound(new Uint8Array([1])); set(-1); fail(() => reducer.takeOutbound(), 'clock-invalid'); assert.equal(reducer.snapshot().outboundCount, 0); const connecting = new TransportStateReducer({ nowMs: () => 0 }); connecting.start(); connecting.cancel(); assert.equal(connecting.snapshot().state, 'cancelled'); });
test('trace retains bounded frozen chronology without payloads or tokens', () => { let now = 0; const reducer = new TransportStateReducer({ nowMs: () => now++ }); reducer.start(); reducer.markOpen(); for (let i = 0; i < Math.ceil(MAX_TRACE_ENTRIES / 3) + 10; i++) { reducer.enqueueOutbound(new Uint8Array([1])); const item = reducer.takeOutbound(); reducer.commitOutbound(item.token, item.frame.byteLength); } const trace = reducer.trace(); assert.equal(trace.length, MAX_TRACE_ENTRIES); assert.ok(trace.every(Object.isFrozen)); assert.deepEqual(trace.slice(-3).map(({ event }) => event), ['enqueueOutbound', 'takeOutbound', 'commitOutbound']); assert.ok(trace.every(row => !Object.keys(row).some(key => /payload|token/i.test(key)))); });
test('fixture strict validation rejects every schema and live-marker mutation', async () => { const fixture = await happyFixture(); assert.throws(() => validateFixture({ ...fixture, unknown: true })); for (const key of FIXTURE_KEYS) { const mutation = { ...fixture }; delete mutation[key]; assert.throws(() => validateFixture(mutation)); } for (const [key, value] of [['kind', 'other'], ['synthetic', false], ['notLive', false], ['source', 'user-authored']]) assert.throws(() => validateFixture({ ...fixture, [key]: value })); for (const key of ['outboundHex', 'inboundHex']) for (const value of ['', '0', 'abc', '00g1']) assert.throws(() => validateFixture({ ...fixture, [key]: value })); assert.throws(() => validateFixture({ ...fixture, events: [...EXPECTED_EVENTS, 'unexpected'] })); for (const marker of ['https://x', 'wss://x', 'host=x', 'hostname=x', 'domain=x', 'endpoint=x', '192.0.2.1', 'address=x', 'port=1', 'telegram', 'dc2', 'api_id', 'apiHash', 'credential', 'token', 'password', 'phone', 'OTP']) assert.throws(() => validateFixture({ ...fixture, source: marker })); });
test('validated fixture drives transport lifecycle', async () => { const fixture = await happyFixture(); const { reducer } = open(); reducer.enqueueOutbound(decodeHex(fixture.outboundHex)); reducer.receiveInbound(decodeHex(fixture.inboundHex)); const outbound = reducer.takeOutbound(); assert.deepEqual([...outbound.frame], [...decodeHex(fixture.outboundHex)]); reducer.commitOutbound(outbound.token, outbound.frame.byteLength); assert.deepEqual([...reducer.takeInbound()], [...decodeHex(fixture.inboundHex)]); reducer.beginClose(); reducer.markClosed(); assert.deepEqual(reducer.trace().map(({ event }) => event), fixture.events); });
