export const TransportState = { idle: 'idle', connecting: 'connecting', open: 'open', closing: 'closing', closed: 'closed', failed: 'failed', cancelled: 'cancelled' } as const;
export type TransportState = (typeof TransportState)[keyof typeof TransportState];
export const MAX_FRAME_BYTES = 64 * 1024, MAX_QUEUED_FRAMES = 64, MAX_QUEUED_BYTES = 1024 * 1024, MAX_TRACE_ENTRIES = 128;
export type TransportErrorCode = 'clock-invalid' | 'invalid-input' | 'resource-limit' | 'invalid-transition' | 'timeout' | 'error' | 'closed';
export class TransportStateError extends Error { readonly code: TransportErrorCode; constructor(code: TransportErrorCode) { super(code); this.name = 'TransportStateError'; this.code = code; } }
export interface TransportClock { nowMs(): number }
type Item = { frame: Uint8Array }; const terminal = new Set<TransportState>(['closed', 'failed', 'cancelled']);
export class TransportStateReducer {
  private readonly clock: TransportClock;
  private state: TransportState = 'idle'; private inbound: Item[] = []; private outbound: Item[] = []; private inboundBytes = 0; private outboundBytes = 0; private flight?: { token: number; item: Item }; private token = 1; private last?: number; private code?: TransportErrorCode; private history: Record<string, unknown>[] = [];
  constructor(clock: TransportClock) { this.clock = clock; }
  private clear() { for (const x of [...this.inbound, ...this.outbound, ...(this.flight ? [this.flight.item] : [])]) x.frame.fill(0); this.inbound = []; this.outbound = []; this.inboundBytes = 0; this.outboundBytes = 0; this.flight = undefined; }
  private row(from: TransportState, event: string, atMs: number) { const x: Record<string, unknown> = { from, event, to: this.state, atMs, inboundCount: this.inbound.length, outboundCount: this.outbound.length, inboundBytes: this.inboundBytes, outboundBytes: this.outboundBytes }; if (this.code) x.errorCode = this.code; return Object.freeze(x); }
  private append(from: TransportState, event: string, atMs: number) { this.history.push(this.row(from, event, atMs)); if (this.history.length > MAX_TRACE_ENTRIES) this.history.splice(0, this.history.length - MAX_TRACE_ENTRIES); }
  private fail(code: TransportErrorCode, event: string, atMs: number): never { const from = this.state; this.clear(); this.state = 'failed'; this.code = code; this.append(from, event, atMs); throw new TransportStateError(code); }
  private at(event: string) { if (terminal.has(this.state)) throw new TransportStateError('closed'); let n: number; try { n = this.clock.nowMs(); } catch { return this.fail('clock-invalid', event, this.last ?? 0); } if (!Number.isSafeInteger(n) || n < 0 || (this.last !== undefined && n < this.last)) return this.fail('clock-invalid', event, this.last ?? 0); this.last = n; return n; }
  private transition(event: string, expected: TransportState, next: TransportState) { const at = this.at(event); if (this.state !== expected) this.fail('invalid-transition', event, at); const from = this.state; this.state = next; this.append(from, event, at); }
  start() { this.transition('start', 'idle', 'connecting') } connect() { this.start() } markOpen() { this.transition('markOpen', 'connecting', 'open') } beginClose() { this.transition('beginClose', 'open', 'closing') } markClosed() { this.transition('markClosed', 'closing', 'closed'); this.clear() }
  cancel() { const at = this.at('cancel'), from = this.state; this.clear(); this.state = 'cancelled'; this.append(from, 'cancel', at); } timeout() { return this.fail('timeout', 'timeout', this.at('timeout')) } error() { return this.fail('error', 'error', this.at('error')) }
  private valid(x: unknown, event: string, at: number): asserts x is Uint8Array { if (!(x instanceof Uint8Array) || !x.byteLength || x.byteLength > MAX_FRAME_BYTES) this.fail('invalid-input', event, at); }
  enqueueOutbound(frame: Uint8Array) { const at = this.at('enqueueOutbound'); if (this.state !== 'open') this.fail('invalid-transition', 'enqueueOutbound', at); this.valid(frame, 'enqueueOutbound', at); if (this.outbound.length >= MAX_QUEUED_FRAMES || this.outboundBytes + frame.byteLength > MAX_QUEUED_BYTES) this.fail('resource-limit', 'enqueueOutbound', at); this.outbound.push({ frame: new Uint8Array(frame) }); this.outboundBytes += frame.byteLength; this.append('open', 'enqueueOutbound', at); }
  receiveInbound(frame: Uint8Array) { const at = this.at('receiveInbound'); if (this.state !== 'open') this.fail('invalid-transition', 'receiveInbound', at); this.valid(frame, 'receiveInbound', at); if (this.inbound.length >= MAX_QUEUED_FRAMES || this.inboundBytes + frame.byteLength > MAX_QUEUED_BYTES) this.fail('resource-limit', 'receiveInbound', at); this.inbound.push({ frame: new Uint8Array(frame) }); this.inboundBytes += frame.byteLength; this.append('open', 'receiveInbound', at); }
  takeOutbound() { const at = this.at('takeOutbound'); if (this.state !== 'open') this.fail('invalid-transition', 'takeOutbound', at); if (this.flight || !this.outbound.length) return undefined; if (!Number.isSafeInteger(this.token)) this.fail('resource-limit', 'takeOutbound', at); const item = this.outbound[0], token = this.token++; this.flight = { token, item }; this.append('open', 'takeOutbound', at); return { token, frame: new Uint8Array(item.frame) }; }
  commitOutbound(token: number, byteLength: number) { const at = this.at('commitOutbound'); if (this.state !== 'open') this.fail('invalid-transition', 'commitOutbound', at); if (!this.flight || token !== this.flight.token || byteLength !== this.flight.item.frame.byteLength) this.fail('invalid-input', 'commitOutbound', at); const item = this.outbound.shift()!; item.frame.fill(0); this.outboundBytes -= byteLength; this.flight = undefined; this.append('open', 'commitOutbound', at); }
  takeInbound() { const at = this.at('takeInbound'); if (this.state !== 'open') this.fail('invalid-transition', 'takeInbound', at); const item = this.inbound.shift(); if (!item) return undefined; this.inboundBytes -= item.frame.byteLength; const out = new Uint8Array(item.frame); item.frame.fill(0); this.append('open', 'takeInbound', at); return out; }
  snapshot() { const x: Record<string, unknown> = { state: this.state, inboundCount: this.inbound.length, outboundCount: this.outbound.length, inboundBytes: this.inboundBytes, outboundBytes: this.outboundBytes, inFlight: !!this.flight }; if (this.code) x.errorCode = this.code; return Object.freeze(x); } trace() { return Object.freeze(this.history.slice()); }
}
